---
ENVIRONMENT:
    MAX_EPISODE_STEPS: 500
SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENT_0:
        SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
    FORWARD_STEP_SIZE: 0.25
    TURN_ANGLE: 15
    HABITAT_SIM_V0:
        GPU_DEVICE_ID: 0
        ALLOW_SLIDING: true
    RGB_SENSOR:
        WIDTH: 512
        HEIGHT: 512
        HFOV: 90
        TYPE: HabitatSimRGBSensor
    DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256

TASK:
    TYPE: VLN-v0
    POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, LOOK_UP, LOOK_DOWN]
    SUCCESS_DISTANCE: 3.0

    MEASUREMENTS: [STEPS_TAKEN, PATH_LENGTH, DISTANCE_TO_GOAL, SUCCESS, ORACLE_SUCCESS, SPL, NDTW]

    SUCCESS:
        SUCCESS_DISTANCE: 3.0
    NDTW:
        GT_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}_gt.json.gz

DATASET:
    TYPE: RxR-VLN-CE-v1
    SPLIT: train
    ROLES: [guide] # "*", "guide", "follower"
    LANGUAGES: [en-US] #  "*", "te-IN", "hi-IN", "en-US", "en-IN"
    DATA_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}.json.gz
    SCENES_DIR: data/scene_datasets/
